ports:
  - port: 9000
    onOpen: open-preview

tasks:
  - init: composer update
    command: php -S 0.0.0.0:9000 -t public/

vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client
